### ISSUE TITLE
Guidance for use with ssh ProxyCommand

### ISSUE THREAD

**Issue by dmcd** [cloudposse/sudosh#8]
Hi there,

I'm trying to use this with my own Bastion host (unfortunately I can't use `cloudposse/bastion`). I want to be able to use the `ProxyCommand` so that I can pass my private key through to the target host, however if I do this, the sudo logs are encrypted.

I'm using the following ssh config:

```
HOST remote-server
  IdentityFile ~/key.pem
  ForwardAgent yes
  ProxyCommand ssh ec2-user@bastion-ip nc %h %p
```

I've also tried the `ProxyCommand` with `-W` but this seems to require turning on `AllowTcpForwarding` and nothing is captured in the sudo logs. 

Cheers

**Comment by osterman** [comment]
@dmcd, Yes, you're doing everything correctly. Unfortunately, that's the expected behavior & it's not possible to capture clear-text output if using `nc` with `ProxyCommand`, since you're basically logging the encrypted tunnel. In fact, I recommend removing `nc` from the `bastion` container to prevent this behavior. 

Your best alternative is to modify your commands to use a nested `ssh` and leverage ssh-agent forwarding to make it as seamless as possible.

E.g. To run `uptime` on a server called `foobar` from the `bastion`, you would run:

```bash
$ ssh -A bastion.ourcompany.com ssh foobar uptime
```

Alternatively, you can maybe use `ForceCommand` to force an automatic ssh to `foobar`, making it more "transparent" to the user, but there's no way that I know of to combine `%h` with `ForceCommand`

**Comment by dmcd** [comment]
Awesome! thanks @osterman, I've removed nc from the bastion. I have ssh-agent forwarding working and can now see the sudo logs in clear-text.

For anyone else, this is how I set it up:

```
HOST bastion-ip
  IdentityFile ~/key.pem
  ForwardAgent yes
```
```
$ ssh-add remote-server-key.pem
```
Then I can ssh with:
```
$ssh -A -t ec2-user@bastion-ip ssh ec2-user@remote-server-ip
```
I needed to add -t to get round the following error:
```
Pseudo-terminal will not be allocated because stdin is not a terminal.
```

**Comment by osterman** [comment]
Awesome! Thanks for sharing your solution so that it can benefit others. 

Btw, I recommend dropping `IdentityFile` in your `.ssh/config` and relying on your agent to handle all authentication; just make sure you add all SSH keys to your agent. You can also drop the `-A` on the command line, since this is redundant with `ForwardAgent yes` option.  There is probably a config option for `-t`, but don't recall what it is.
