### ISSUE TITLE
FreeBSD Build Fails

### ISSUE THREAD

**Issue by aihealthllc** [cloudposse/sudosh#9]
I’m trying to build sudosh under FreeBSD (11.0-REL).  Before contemplating any external builds, I routinely install the following packages (which many other github ports rely on for builds):

```
pkg install -y autoconf automake m4
```

I’m getting the following error during make of `sudosh`:

```
make: "/usr/share/mk/sys.mk" line 424: Cannot open /etc/make.conf
make: Fatal errors encountered -- cannot continue
```

The stock FreeBSD does have `sys.mk` files in various places:
```
% locate sys.mk
- /usr/share/mk/bsd.sys.mk
- /usr/share/mk/meta.sys.mk
- /usr/share/mk/sys.mk
```

Can someone help me with the make?  The Makefile doesn’t reference `sys.mk` - the reference seems to be coming from somewhere else (perhaps one of the nasty `curl` auto-includes).

Also, please note that the default installation (per the README.mc) expects to see:
- `/etc/sudoers.d/sudosh`
- `/usr/bin/sudoreplay`

… and the politically correct place for these on FreeBSD is:

- `/usr/local/etc/sudosh.conf`  (if you want a config independent of sudo's config)
- `/usr/local/etc/sudoers` (if you want to share sudo's config)
- `/usr/local/bin/sudoreplay`  (default baseline installation location)

In addition, I'm curious what the default log location is for this binary.

**Comment by osterman** [comment]
This is something funky with the the current BSD setup. Presumably one of the `.mk` files is calling `include /etc/make.conf` which will abort if it doesn't exist. 

According to the following resource, the `make.conf` file is just a regular `Makefile` (with a `.conf` extension) that lets you define ENVs (or other make-isms) for your global build environment.

http://easyos.net/articles/bsd/freebsd/optimization_by_make_conf_in_freebsd

Thus, unless you need to set any global ENVs, running `sudo touch /etc/make.conf` will resolve that particular error.

Fwiw, we're compiling it on OSX/Darwin and Linux and cross-compiling for BSD in TravisCI builds.

>  please note that the default installation (per the README.mc) expects to see

The `README.md` is just a lose guide for how to set it up. If BSD supports a `sudoers` file in `/usr/local/etc/...` go for it. That's not conventional on Linux or Darwin out-of-the-box for `sudo`. Since `sudo` is a system utility, it will typically not use `/usr/local/etc`. 

Also, there might be some confusion here; `sudosh` *does not* rely on any configuration files. We're just suggesting how `sudo` should be configured to be compatible with this wrapper.

You'll note that the [source](https://github.com/cloudposse/sudosh/blob/master/main.go) (~100 lines of code) does not reference any hardcoded paths. If your `PATH` is setup correctly, it should find the binaries.

**Comment by aihealthllc** [comment]
All of my FreeBSD systems have an /etc/make.conf as part of my standard deployment, so the file definitely exists (and at this point of FreeBSD maturity, contains nothing fancy).  Your article source is a bit dated (2012), however.  The non-OS files (packages/ports) tend to rely on /etc/src.conf, which I also have.

 In conclusion, “sudo touch /etc/make.conf” won’t resolve this build issue, since the file is already present.  I’d like to help resolve the build issue, but need a clue as to what to look at next.

My apologies for combining multiple topics in my original bug report – I was just wanting to point out the discrepancy in the README as far as the path and naming of the sudoers file (which might confuse FreeBSD users)… I realize it’s not needed just to run this shell.

Since I’m automating a network of FreeBSD servers via cfEngine, I just wanted to have a standardized install.  There used to be a sudosh port available a long time ago, which made it a one-line (automated if desired) install on FreeBSD.  I could just as easily have cfEngine grab the source and massage it… but that leaves the FreeBSD world without a working build.

**Comment by osterman** [comment]
What are the filesystem permissions on `/etc/make.conf`? 
Can you run `strace` (or the equivalent on BSD) to identify the system calls that are failing?

**Comment by osterman** [comment]
Also, fwiw, here are the `make` targets we're leveraging. 
https://github.com/cloudposse/sudosh/blob/master/.travis.yml

They are defined here:
https://github.com/cloudposse/build-harness/blob/master/modules/go/Makefile.build

`make` is just a convenience. It's possible to run the commands in the referenced targets by hand.

**Comment by osterman** [comment]
Maybe try gmake (GNU Make) which is what we built this with. http://nullprogram.com/blog/2017/08/20/
